name: PixliesHungergames
version: '${project.version}'
main: org.pixlies.pixlieshungergames.PixliesHungergames
api-version: 1.19
authors: [Machmeinparaillegal]
commands:
  setspawn:
      description: Set possible spawnpoints for when the games start!
permissions:
  pixlies.staff.hungergames.setspawnpoints:
    description: Allows user to set spawnpoints for Hungergames
    default: op
